@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.example.designpatterns.behavioral.memento.caretaker.MementoPatternDemo#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.example.designpatterns.behavioral.memento.caretaker.MementoPatternDemo",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1611567195 { 
   	label=designpatterns
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_2028016971 { 
   	label=MementoPatternDemo
	labeljust=l
	fillcolor=white
	style=filled
   
   MementoPatternDemo1016128813XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="MementoPatternDemo

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_936147233 { 
   	label=Caretaker
	labeljust=l
	fillcolor=white
	style=filled
   
   Caretaker1016128813XXXadd1681334247[
	label="+ add()"
	style=filled
	fillcolor=white
	tooltip="Caretaker

null"
	fontcolor=darkgreen
];

Caretaker1016128813XXXget104431[
	label="+ get()"
	style=filled
	fillcolor=white
	tooltip="Caretaker

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_990475159 { 
   	label=Originator
	labeljust=l
	fillcolor=white
	style=filled
   
   Originator1016128813XXXgetStateFromMemento1681334247[
	label="+ getStateFromMemento()"
	style=filled
	fillcolor=white
	tooltip="Originator

null"
	fontcolor=darkgreen
];

Originator1016128813XXXsaveStateToMemento0[
	label="+ saveStateToMemento()"
	style=filled
	fillcolor=white
	tooltip="Originator

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
MementoPatternDemo1016128813XXXmain1859653459 -> Caretaker1016128813XXXadd1681334247;
MementoPatternDemo1016128813XXXmain1859653459 -> Caretaker1016128813XXXget104431;
MementoPatternDemo1016128813XXXmain1859653459 -> Originator1016128813XXXgetStateFromMemento1681334247;
MementoPatternDemo1016128813XXXmain1859653459 -> Originator1016128813XXXsaveStateToMemento0;
    
}
@enduml